services:
  redis:
    image: redis:latest
    networks:
      - my-network
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - my-network
networks:
  my-network:
    driver: bridge