services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: sapassword
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: sapassword
    ports:
      - "3306:3306"