services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"